### ISSUE TITLE
Checklist for RUBION-Users

### ISSUE THREAD

**Issue by patta42** [patta42/website#123]
- [x] List
  - [x] Filters:
    - [x] By methods
    - [x] By state (active/inactive)
  - [x] Customizable List Content
- [ ] Edit
  - [x] Show Overview 
  - [ ] Easy entering of Safety Instructions
- [x] Inactivate
  - [ ] Send mail to user
  - [ ] Send mail to workgroup head
- [ ] Activate
- [x] Move to another group
- [x] Show changes  
- [x] Create without user input
