### ISSUE TITLE
Checklist for Workgroups

### ISSUE THREAD

**Issue by patta42** [patta42/website#124]
- [ ] List
  - [ ] Filters
    - [ ] By methods
    - [x] By state (active/inactive)
  - [x] Customizable list content
- [x] Edit
  - [x] Show overview
  - [x] Change group leader
  - [x] Change "may add members"
  - [x] Change "may add projects" 
- [ ] Inactivate
  - [ ] Mail to group leader
  - [ ] Mail to members
- [ ] Show Results (papers, theses, ...)
- [ ] Create from scratch
  - [x] external group leader
  - [x] group leader from existing RUBION user
  - [x] group leader from existing Staff
  - [ ] group leader from new RUB Id
