### ISSUE TITLE
Checklist for Projects

### ISSUE THREAD

**Issue by patta42** [patta42/website#125]
- [ ] List
  - [ ] Customizable Content in List
    - [ ] Publications, Theses, ...
  - [ ] Filters
    - [x] by state (active/inactive)
    - [ ] by methods
- [ ] Inactivate   
  - [ ] Mail to group leader
  - [ ] Mail to members
- [ ] Extend project
- [x] Move to other group
- [x] Edit
- [ ] Apply for beamtime (or other time for resources)
- [ ] Create
