### ISSUE TITLE
Checklist for Beirat

### ISSUE THREAD

**Issue by patta42** [patta42/website#126]
- [x] List current Beirat
- [x] Change Beirat members
- [ ] Add new positions in Beirat
  - [ ] restrict to users with permission
- [ ] Remove positions in Beirat
  - [ ] restrict to users with permission
- [ ] Edit positions in Beirat
  - [ ] restrict to users with permission
