### ISSUE TITLE
Checklist for Courses

### ISSUE THREAD

**Issue by patta42** [patta42/website#128]
*Note*: Courses refers to the single course dates.

- [ ] List
  - [ ] Customizable content
  - [ ] Filters
    - [x] upcoming/current/all
    - [x] By course type
    - [ ] By "organised by RUBION"
- [x] Create
- [ ] Edit
  - [ ] Easy way to edit script
   
- [ ] Administer participants
  - [x] List 
    - [x] Restrict to attendee-type
    - [x] Restrict to waitlist/no waitlist
  - [x] Email to selected attendees
  - [x] Email course results to selected attendees (allow editing template)
  - [x] Delete selected attendees (no mail will be send!)
  - [ ] Move selected attendees to other course of...
    - [x] same type
      - [ ] Send mail automatically, allow edit first 
  - [x] inline edit 
    - [x] add exam result
    - [x] change passed/not passed
    - [x] change paid/not paid
    - [x] change student course  
  - [x] create PDFs
     - [x] for nameplates
     - [x] for certificates
